apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-00a9f89d1ba6dd852
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-065272c55a0309848
      us-east-1b:
        id: subnet-0c3894c412ae45246
    private:
      us-east-1a:
        id: subnet-0ef39d43d72e838a4
      us-east-1b:
        id: subnet-081f7e84978407824
nodeGroups:
  - name: EKS-public-workers
    instanceType: t3.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
